"""empty message

Revision ID: 05f8509b3ee1
Revises: f23ec267170c
Create Date: 2019-01-18 15:14:24.892691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05f8509b3ee1'
down_revision = 'f23ec267170c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marriage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('married_to_id', sa.Integer(), nullable=False),
    sa.Column('dateOfWedding', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['married_to_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marriage')
    # ### end Alembic commands ###
