"""empty message

Revision ID: 52cdbfb06ef0
Revises: 7eea55a07cac
Create Date: 2019-01-19 18:02:29.884097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cdbfb06ef0'
down_revision = '7eea55a07cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marriage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bride_id', sa.Integer(), nullable=False),
    sa.Column('groom_id', sa.Integer(), nullable=False),
    sa.Column('dateOfWedding', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bride_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['groom_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marriage')
    # ### end Alembic commands ###
