"""empty message

Revision ID: 77a61b3e870b
Revises: 
Create Date: 2019-01-16 12:26:35.401459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77a61b3e870b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('dateOfDeath', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Kinship',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Kinship')
    op.drop_table('person')
    # ### end Alembic commands ###
