"""empty message

Revision ID: 7eea55a07cac
Revises: 05f8509b3ee1
Create Date: 2019-01-19 17:46:29.540110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eea55a07cac'
down_revision = '05f8509b3ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marriage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marriage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('married_to_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dateOfWedding', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['married_to_id'], ['person.id'], name='marriage_married_to_id_fkey'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='marriage_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='marriage_pkey')
    )
    # ### end Alembic commands ###
