"""empty message

Revision ID: f23ec267170c
Revises: 77a61b3e870b
Create Date: 2019-01-16 12:33:10.159571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23ec267170c'
down_revision = '77a61b3e870b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kinship',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.drop_table('Kinship')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Kinship',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['person.id'], name='Kinship_child_id_fkey'),
    sa.ForeignKeyConstraint(['parent_id'], ['person.id'], name='Kinship_parent_id_fkey'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id', name='Kinship_pkey')
    )
    op.drop_table('kinship')
    # ### end Alembic commands ###
