"""empty message

Revision ID: 5a5b0e24eb68
Revises: 
Create Date: 2019-01-30 20:29:31.860580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5b0e24eb68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=True),
    sa.Column('dateOfDeath', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kinship',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('marriage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bride_id', sa.Integer(), nullable=False),
    sa.Column('groom_id', sa.Integer(), nullable=False),
    sa.Column('dateOfWedding', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bride_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['groom_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marriage')
    op.drop_table('kinship')
    op.drop_table('person')
    # ### end Alembic commands ###
